"""Auto-generated variant data from VCF parsing."""

from alphagenome.models import dna_client

ALL_VARIANTS = [
    {
        'name': 'CEP104_chr1_3836304',
        'gene': 'CEP104',
        'chromosome': 'chr1',
        'position': 3836304,
        'ref': 'CAA',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'TARDBP_chr1_11017202',
        'gene': 'TARDBP',
        'chromosome': 'chr1',
        'position': 11017202,
        'ref': 'CT',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'MTOR_chr1_11255846',
        'gene': 'MTOR',
        'chromosome': 'chr1',
        'position': 11255846,
        'ref': 'C',
        'alt': 'CA',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'NPPA_chr1_11846911',
        'gene': 'NPPA',
        'chromosome': 'chr1',
        'position': 11846911,
        'ref': 'GCC',
        'alt': 'G',
        'type': 'downstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'MFN2_chr1_11981920',
        'gene': 'MFN2',
        'chromosome': 'chr1',
        'position': 11981920,
        'ref': 'G',
        'alt': 'GTTTTTTT',
        'type': '5_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'MFN2_chr1_11997038',
        'gene': 'MFN2',
        'chromosome': 'chr1',
        'position': 11997038,
        'ref': 'CAA',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'PRAMEF18_chr1_13223649',
        'gene': 'PRAMEF18',
        'chromosome': 'chr1',
        'position': 13223649,
        'ref': 'G',
        'alt': 'A',
        'type': 'missense_variant',
        'disease': 'not specified',
        'clinvar_classification': 'Uncertain_significance',
        'analysis_strategy': 'RNA_SEQ, SPLICE_JUNCTIONS',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.SPLICE_JUNCTIONS],
        'interval_size': 1048576,
    },
    {
        'name': 'SDHB_chr1_17053700',
        'gene': 'SDHB',
        'chromosome': 'chr1',
        'position': 17053700,
        'ref': 'TC',
        'alt': 'T,TCC',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DDOST_chr1_20651801',
        'gene': 'DDOST',
        'chromosome': 'chr1',
        'position': 20651801,
        'ref': 'TTTTATTTATTTA',
        'alt': 'T,TTTTATTTA',
        'type': '3_prime_UTR_variant',
        'disease': 'Congenital disorder of glycosylation|Parkinson Disease, Recessive',
        'clinvar_classification': 'Benign/Likely_benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DDOST_chr1_20655167',
        'gene': 'DDOST',
        'chromosome': 'chr1',
        'position': 20655167,
        'ref': 'TTTTG',
        'alt': 'T',
        'type': 'upstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'ALPL_chr1_21576264',
        'gene': 'ALPL',
        'chromosome': 'chr1',
        'position': 21576264,
        'ref': 'TG',
        'alt': 'T',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'ALPL_chr1_21576267',
        'gene': 'ALPL',
        'chromosome': 'chr1',
        'position': 21576267,
        'ref': 'ATGGG',
        'alt': 'A',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'C1QB_chr1_22659292',
        'gene': 'C1QB',
        'chromosome': 'chr1',
        'position': 22659292,
        'ref': 'A',
        'alt': 'AGATG',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'HMGCL_chr1_23825731',
        'gene': 'HMGCL',
        'chromosome': 'chr1',
        'position': 23825731,
        'ref': 'TCCAAAAAAAAAAAAAAAAA',
        'alt': 'T',
        'type': 'upstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'ARID1A_chr1_26780772',
        'gene': 'ARID1A',
        'chromosome': 'chr1',
        'position': 26780772,
        'ref': 'T',
        'alt': 'TC',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'CCDC28B_chr1_32205464',
        'gene': 'CCDC28B',
        'chromosome': 'chr1',
        'position': 32205464,
        'ref': 'A',
        'alt': 'C',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'MACF1_chr1_39434386',
        'gene': 'MACF1',
        'chromosome': 'chr1',
        'position': 39434386,
        'ref': 'CT',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SLC2A1_chr1_42943295',
        'gene': 'SLC2A1',
        'chromosome': 'chr1',
        'position': 42943295,
        'ref': 'G',
        'alt': 'A',
        'type': 'synonymous_variant',
        'disease': 'not provided|Hereditary cryohydrocytosis with reduced stomatin|Inborn genetic diseases|GLUT1 deficiency syndrome 1, autosomal recessive|Encephalopathy due to GLUT1 deficiency|Childhood onset GLUT1 deficiency syndrome 2|not specified|Dystonia 9',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, SPLICE_JUNCTIONS',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.SPLICE_JUNCTIONS],
        'interval_size': 1048576,
    },
    {
        'name': 'SLC6A9_chr1_44017368',
        'gene': 'SLC6A9',
        'chromosome': 'chr1',
        'position': 44017368,
        'ref': 'AACACAC',
        'alt': 'A,AACAC',
        'type': 'upstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'MMACHC_chr1_45509416',
        'gene': 'MMACHC',
        'chromosome': 'chr1',
        'position': 45509416,
        'ref': 'G',
        'alt': 'GTTTTT',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'STIL_chr1_47272448',
        'gene': 'STIL',
        'chromosome': 'chr1',
        'position': 47272448,
        'ref': 'ATT',
        'alt': 'A',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'STIL_chr1_47300473',
        'gene': 'STIL',
        'chromosome': 'chr1',
        'position': 47300473,
        'ref': 'T',
        'alt': 'TTC',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DOCK7_chr1_62578974',
        'gene': 'DOCK7',
        'chromosome': 'chr1',
        'position': 62578974,
        'ref': 'C',
        'alt': 'CA',
        'type': 'intron_variant',
        'disease': 'Developmental and epileptic encephalopathy, 23|not specified|not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'LEPR_chr1_65592521',
        'gene': 'LEPR',
        'chromosome': 'chr1',
        'position': 65592521,
        'ref': 'G',
        'alt': 'GT',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SLC35D1_chr1_67021691',
        'gene': 'SLC35D1',
        'chromosome': 'chr1',
        'position': 67021691,
        'ref': 'TCCAACA',
        'alt': 'T',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'CTH_chr1_70438840',
        'gene': 'CTH',
        'chromosome': 'chr1',
        'position': 70438840,
        'ref': 'T',
        'alt': 'TTGTG',
        'type': 'intron_variant',
        'disease': 'not provided|Cystathioninuria',
        'clinvar_classification': 'Likely_benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'GLMN_chr1_92267703',
        'gene': 'GLMN',
        'chromosome': 'chr1',
        'position': 92267703,
        'ref': 'CA',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'GFI1_chr1_92478757',
        'gene': 'GFI1',
        'chromosome': 'chr1',
        'position': 92478757,
        'ref': 'CAGAGAG',
        'alt': 'C,CAGAGAGAGAGAG',
        'type': 'splice_region_variant&intron_variant',
        'disease': 'Neutropenia, severe congenital, 2, autosomal dominant|not provided|Severe congenital neutropenia|Nonimmune chronic idiopathic neutropenia of adults',
        'clinvar_classification': 'Benign/Likely_benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SLC35A3_chr1_100011683',
        'gene': 'SLC35A3',
        'chromosome': 'chr1',
        'position': 100011683,
        'ref': 'ATTATTTATTTAT',
        'alt': 'A',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SLC35A3_chr1_100015152',
        'gene': 'SLC35A3',
        'chromosome': 'chr1',
        'position': 100015152,
        'ref': 'C',
        'alt': 'T',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DBT_chr1_100186848',
        'gene': 'DBT',
        'chromosome': 'chr1',
        'position': 100186848,
        'ref': 'C',
        'alt': 'CACAT,CAT',
        'type': 'downstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'DBT_chr1_100189351',
        'gene': 'DBT',
        'chromosome': 'chr1',
        'position': 100189351,
        'ref': 'TA',
        'alt': 'T',
        'type': '3_prime_UTR_variant',
        'disease': 'Maple syrup urine disease|not provided',
        'clinvar_classification': 'Conflicting_classifications_of_pathogenicity',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DBT_chr1_100189353',
        'gene': 'DBT',
        'chromosome': 'chr1',
        'position': 100189353,
        'ref': 'A',
        'alt': 'T',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided|Maple syrup urine disease',
        'clinvar_classification': 'Uncertain_significance',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DBT_chr1_100191747',
        'gene': 'DBT',
        'chromosome': 'chr1',
        'position': 100191747,
        'ref': 'TATACACACACACACACACACACACACAC',
        'alt': 'T',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'DBT_chr1_100206072',
        'gene': 'DBT',
        'chromosome': 'chr1',
        'position': 100206072,
        'ref': 'TA',
        'alt': 'T',
        'type': 'downstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'CASQ2_chr1_115725557',
        'gene': 'CASQ2',
        'chromosome': 'chr1',
        'position': 115725557,
        'ref': 'GAAAA',
        'alt': 'G',
        'type': 'splice_region_variant&intron_variant',
        'disease': 'Catecholaminergic polymorphic ventricular tachycardia 1|not provided|Cardiomyopathy|not specified|Catecholaminergic polymorphic ventricular tachycardia 2',
        'clinvar_classification': 'Benign/Likely_benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'TBX15_chr1_118926874',
        'gene': 'TBX15',
        'chromosome': 'chr1',
        'position': 118926874,
        'ref': 'TTG',
        'alt': 'T,TTGTG',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'PRPF3_chr1_150328547',
        'gene': 'PRPF3',
        'chromosome': 'chr1',
        'position': 150328547,
        'ref': 'A',
        'alt': 'ATT',
        'type': 'upstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'CTSK_chr1_150807078',
        'gene': 'CTSK',
        'chromosome': 'chr1',
        'position': 150807078,
        'ref': 'TCTCACACA',
        'alt': 'T,TCACACTCACACA',
        'type': 'downstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'CCDST_chr1_152219233',
        'gene': 'CCDST',
        'chromosome': 'chr1',
        'position': 152219233,
        'ref': 'C',
        'alt': 'G',
        'type': 'missense_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, SPLICE_JUNCTIONS',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.SPLICE_JUNCTIONS],
        'interval_size': 1048576,
    },
    {
        'name': 'FLG_chr1_152314865',
        'gene': 'FLG',
        'chromosome': 'chr1',
        'position': 152314865,
        'ref': 'CT',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'GATAD2B_chr1_153816059',
        'gene': 'GATAD2B',
        'chromosome': 'chr1',
        'position': 153816059,
        'ref': 'AACACAC',
        'alt': 'A,AACACACACACACACACAC',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'IL6R_chr1_154437417',
        'gene': 'IL6R',
        'chromosome': 'chr1',
        'position': 154437417,
        'ref': 'A',
        'alt': 'AT',
        'type': 'splice_region_variant&intron_variant',
        'disease': 'IL6R-related disorder|not specified',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SPTA1_chr1_158668075',
        'gene': 'SPTA1',
        'chromosome': 'chr1',
        'position': 158668075,
        'ref': 'GA',
        'alt': 'G',
        'type': 'intron_variant',
        'disease': 'Spherocytosis, Recessive|not provided|Pyropoikilocytosis, hereditary|Elliptocytosis',
        'clinvar_classification': 'Conflicting_classifications_of_pathogenicity',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SDHC_chr1_161362301',
        'gene': 'SDHC',
        'chromosome': 'chr1',
        'position': 161362301,
        'ref': 'CT',
        'alt': 'C',
        'type': 'downstream_gene_variant',
        'disease': 'not specified|not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'DDR2_chr1_162767061',
        'gene': 'DDR2',
        'chromosome': 'chr1',
        'position': 162767061,
        'ref': 'G',
        'alt': 'GAAAA',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'ADCY10_chr1_167904118',
        'gene': 'ADCY10',
        'chromosome': 'chr1',
        'position': 167904118,
        'ref': 'T',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'GPR161_chr1_168090628',
        'gene': 'GPR161',
        'chromosome': 'chr1',
        'position': 168090628,
        'ref': 'A',
        'alt': 'G',
        'type': 'synonymous_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, SPLICE_JUNCTIONS',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.SPLICE_JUNCTIONS],
        'interval_size': 1048576,
    },
    {
        'name': 'LAMC1_chr1_183131172',
        'gene': 'LAMC1',
        'chromosome': 'chr1',
        'position': 183131172,
        'ref': 'C',
        'alt': 'CAAAAA',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'LAMC2_chr1_183207835',
        'gene': 'LAMC2',
        'chromosome': 'chr1',
        'position': 183207835,
        'ref': 'G',
        'alt': 'GTT',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'LAMC2_chr1_183236388',
        'gene': 'LAMC2',
        'chromosome': 'chr1',
        'position': 183236388,
        'ref': 'CA',
        'alt': 'C',
        'type': 'downstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'CDC73_chr1_193135868',
        'gene': 'CDC73',
        'chromosome': 'chr1',
        'position': 193135868,
        'ref': 'C',
        'alt': 'CTT,CT',
        'type': 'upstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'ASPM_chr1_197145845',
        'gene': 'ASPM',
        'chromosome': 'chr1',
        'position': 197145845,
        'ref': 'AATATATAT',
        'alt': 'A,AATAT',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'KIF14_chr1_200606917',
        'gene': 'KIF14',
        'chromosome': 'chr1',
        'position': 200606917,
        'ref': 'G',
        'alt': 'GA',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'KISS1_chr1_204190414',
        'gene': 'KISS1',
        'chromosome': 'chr1',
        'position': 204190414,
        'ref': 'G',
        'alt': 'C',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'IRF6_chr1_209796634',
        'gene': 'IRF6',
        'chromosome': 'chr1',
        'position': 209796634,
        'ref': 'A',
        'alt': 'AACACAC,AAC',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'USH2A_chr1_215640844',
        'gene': 'USH2A',
        'chromosome': 'chr1',
        'position': 215640844,
        'ref': 'CA',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'USH2A_chr1_215743371',
        'gene': 'USH2A',
        'chromosome': 'chr1',
        'position': 215743371,
        'ref': 'C',
        'alt': 'CAT',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'TGFB2_chr1_218437320',
        'gene': 'TGFB2',
        'chromosome': 'chr1',
        'position': 218437320,
        'ref': 'CTT',
        'alt': 'C',
        'type': 'splice_region_variant&intron_variant',
        'disease': 'Loeys-Dietz syndrome 4|not specified',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'SLC30A10_chr1_219927663',
        'gene': 'SLC30A10',
        'chromosome': 'chr1',
        'position': 219927663,
        'ref': 'A',
        'alt': 'C',
        'type': 'upstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'EPHX1_chr1_225839366',
        'gene': 'EPHX1',
        'chromosome': 'chr1',
        'position': 225839366,
        'ref': 'G',
        'alt': 'GGT',
        'type': 'downstream_gene_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'ATAC, RNA_SEQ',
        'outputs': [dna_client.OutputType.ATAC, dna_client.OutputType.RNA_SEQ],
        'interval_size': 1048576,
    },
    {
        'name': 'COG2_chr1_230683409',
        'gene': 'COG2',
        'chromosome': 'chr1',
        'position': 230683409,
        'ref': 'TA',
        'alt': 'T',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'TBCE_chr1_235380161',
        'gene': 'TBCE',
        'chromosome': 'chr1',
        'position': 235380161,
        'ref': 'TTGTGTGTGTGTGTGTGTGTG',
        'alt': 'T,TTGTGTGTG',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'NID1_chr1_236045206',
        'gene': 'NID1',
        'chromosome': 'chr1',
        'position': 236045206,
        'ref': 'CAAAAAAAA',
        'alt': 'C,CAAAAAAA',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'ACTN2_chr1_236761432',
        'gene': 'ACTN2',
        'chromosome': 'chr1',
        'position': 236761432,
        'ref': 'C',
        'alt': 'CGTGT,CAT',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'MTR_chr1_236852256',
        'gene': 'MTR',
        'chromosome': 'chr1',
        'position': 236852256,
        'ref': 'CGT',
        'alt': 'C',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'RYR2_chr1_237731891',
        'gene': 'RYR2',
        'chromosome': 'chr1',
        'position': 237731891,
        'ref': 'T',
        'alt': 'TACACACACAC,TAC',
        'type': 'intron_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'CHRM3_chr1_239909421',
        'gene': 'CHRM3',
        'chromosome': 'chr1',
        'position': 239909421,
        'ref': 'G',
        'alt': 'GAA',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'FH_chr1_241500602',
        'gene': 'FH',
        'chromosome': 'chr1',
        'position': 241500602,
        'ref': 'T',
        'alt': 'TGA',
        'type': 'intron_variant',
        'disease': 'not specified|not provided|Hereditary leiomyomatosis and renal cell cancer|Fumarase deficiency|Hereditary cancer-predisposing syndrome',
        'clinvar_classification': 'Conflicting_classifications_of_pathogenicity',
        'analysis_strategy': 'SPLICE_JUNCTIONS, ATAC',
        'outputs': [dna_client.OutputType.SPLICE_JUNCTIONS, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
    {
        'name': 'HNRNPU_chr1_244854162',
        'gene': 'HNRNPU',
        'chromosome': 'chr1',
        'position': 244854162,
        'ref': 'TA',
        'alt': 'T',
        'type': '3_prime_UTR_variant',
        'disease': 'not provided',
        'clinvar_classification': 'Likely_benign',
        'analysis_strategy': 'RNA_SEQ, ATAC',
        'outputs': [dna_client.OutputType.RNA_SEQ, dna_client.OutputType.ATAC],
        'interval_size': 1048576,
    },
]
